version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: buslab_mongodb
    restart: always
    ports:
      - "127.0.0.1:${MONGODB_EXPOSE}:${MONGODB_PORT}"
    volumes:
      - mongodb_data:/data/db
    networks:
      - buslab_net
    command: mongod --port ${MONGODB_PORT}

  # Backend API service
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: buslab_backend
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:${MONGODB_PORT}/${MONGO_DATABASE}
    env_file:
      - ./.env
    volumes:
      # Mount logs directory to host machine for persistent log storage
      - ./logs:/app/logs
    networks:
      - buslab_net

volumes:
  mongodb_data:

networks:
  buslab_net:
    driver: bridge